const advancedExercises = [
  { sentence: "Der erfahren__ Lehrer erklärt den schwierig__ Stoff mit großer__ Geduld.", ending: ["e","en","er"], context: "Weak Nom / Weak Acc / Strong Dat" },
  { sentence: "Ein neu__ Mitarbeiter arbeitet an einem wichtig__ Projekt.", ending: ["er","en"], context: "Mixed Nom / Mixed Dat" },
  { sentence: "Die alt__ Brücke über den ruhig__ Fluss wurde renoviert.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Mit frisch__ Zutaten kocht sie ein lecker__ Gericht.", ending: ["en","es"], context: "Strong Dat / Mixed Acc" },
  { sentence: "Der reich__ Unternehmer unterstützt die jung__ Talente.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Aus tief__ Respekt lobte er die ehrlich__ Arbeit.", ending: ["em","e"], context: "Strong Dat / Weak Acc" },
  { sentence: "Ein klein__ Fehler kann große__ Folgen haben.", ending: ["er","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Die modern__ Technik erleichtert den schwierig__ Alltag.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Wegen des schlecht__ Wetters fiel das geplant__ Treffen aus.", ending: ["en","e"], context: "Weak Gen / Weak Nom" },
  { sentence: "Der alt__ Mann mit dem grau__ Bart lächelt freundlich.", ending: ["e","en"], context: "Weak Nom / Weak Dat" },

  { sentence: "Ein klug__ Student stellt dem bekannt__ Professor eine interessant__ Frage.", ending: ["er","en","e"], context: "Mixed Nom / Weak Dat / Mixed Acc" },
  { sentence: "Die schön__ Aussicht von dem hoh__ Berg begeistert alle.", ending: ["e","en"], context: "Weak Nom / Weak Dat" },
  { sentence: "Mit groß__ Interesse liest sie die spannend__ Geschichte.", ending: ["em","e"], context: "Strong Dat / Weak Acc" },
  { sentence: "Ein ehrgeizig__ Ziel erfordert hart__ Arbeit.", ending: ["es","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Die wichtig__ Entscheidung hängt von klar__ Fakten ab.", ending: ["e","en"], context: "Weak Nom / Strong Dat" },
  { sentence: "Trotz hoh__ Kosten bleibt das alt__ Gebäude erhalten.", ending: ["er","e"], context: "Strong Gen / Weak Nom" },
  { sentence: "Der freundlich__ Nachbar hilft den neu__ Bewohnern.", ending: ["e","en"], context: "Weak Nom / Weak Dat" },
  { sentence: "Ein schlecht__ Beispiel zeigt die falsch__ Richtung.", ending: ["es","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Die laut__ Musik stört den konzentriert__ Arbeiter.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Aus alt__ Gewohnheit wählt er den sicher__ Weg.", ending: ["er","en"], context: "Strong Dat / Weak Acc" },

  { sentence: "Ein kreativ__ Kopf findet immer neu__ Lösungen.", ending: ["er","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Die schnell__ Antwort überzeugte den kritisch__ Chef.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Mit ruhig__ Stimme erklärt sie den kompliziert__ Plan.", ending: ["er","en"], context: "Strong Dat / Weak Acc" },
  { sentence: "Ein zuverlässig__ Kollege übernimmt die wichtig__ Aufgaben.", ending: ["er","en"], context: "Mixed Nom / Weak Acc" },
  { sentence: "Der streng__ Lehrer bewertet die schriftlich__ Prüfung.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },
  { sentence: "Trotz groß__ Zweifel folgte er dem mutig__ Entschluss.", ending: ["er","en"], context: "Strong Gen / Weak Dat" },
  { sentence: "Die ehrlich__ Meinung zählt mehr als leer__ Worte.", ending: ["e","e"], context: "Weak Nom / Strong Acc" },
  { sentence: "Ein stark__ Team erreicht gemeinsam groß__ Ziele.", ending: ["es","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Mit klar__ Struktur löst sie den schwierig__ Fall.", ending: ["er","en"], context: "Strong Dat / Weak Acc" },
  { sentence: "Der ruhig__ See spiegelt die blau__ Berge.", ending: ["e","en"], context: "Weak Nom / Strong Acc" },

  { sentence: "Ein alt__ Fehler kann teuer__ Folgen haben.", ending: ["er","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Die tief__ Analyse erklärt die komplex__ Situation.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },
  { sentence: "Mit neu__ Ideen verbessert sie den effizient__ Ablauf.", ending: ["en","en"], context: "Strong Dat / Weak Acc" },
  { sentence: "Ein wertvoll__ Beitrag stärkt das gemeinsam__ Ziel.", ending: ["er","e"], context: "Mixed Nom / Weak Acc" },
  { sentence: "Der kritisch__ Blick erkennt die klein__ Fehler.", ending: ["e","en"], context: "Weak Nom / Strong Acc" },
  { sentence: "Trotz hart__ Arbeit blieb der Erfolg aus.", ending: ["er"], context: "Strong Gen" },
  { sentence: "Die sicher__ Lösung schützt vor groß__ Risiken.", ending: ["e","en"], context: "Weak Nom / Strong Dat" },
  { sentence: "Ein logisch__ Argument überzeugt den skeptisch__ Zuhörer.", ending: ["es","en"], context: "Mixed Nom / Weak Acc" },
  { sentence: "Mit stark__ Willen erreicht man lang__ Ziele.", ending: ["em","e"], context: "Strong Dat / Strong Acc" },
  { sentence: "Der geduldig__ Umgang verbessert das menschlich__ Miteinander.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },

  { sentence: "Ein gut__ Plan verhindert unnötig__ Fehler.", ending: ["er","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Die ruhig__ Atmosphäre fördert konzentriert__ Arbeit.", ending: ["e","e"], context: "Weak Nom / Strong Acc" },
  { sentence: "Mit präzis__ Worten erklärt er den technisch__ Ablauf.", ending: ["en","en"], context: "Strong Dat / Weak Acc" },
  { sentence: "Ein fair__ Urteil schützt die unschuldig__ Person.", ending: ["es","e"], context: "Mixed Nom / Weak Acc" },
  { sentence: "Der positiv__ Eindruck bleibt trotz klein__ Fehler.", ending: ["e","en"], context: "Weak Nom / Strong Dat" },
  { sentence: "Trotz klar__ Regeln kam es zu chaotisch__ Szenen.", ending: ["er","en"], context: "Strong Gen / Strong Dat" },
  { sentence: "Die ruhig__ Hand führt den präzis__ Schnitt.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Ein offen__ Gespräch klärt die missverständlich__ Situation.", ending: ["es","e"], context: "Mixed Nom / Weak Acc" },
  { sentence: "Mit fest__ Entschlossenheit verfolgt sie den mutig__ Plan.", ending: ["er","en"], context: "Strong Dat / Weak Acc" },
  { sentence: "Der respektvoll__ Umgang stärkt das sozial__ Klima.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },
  
  { sentence: "Der erfahren__ Arzt erklärt dem jung__ Patienten die notwendig__ Behandlung.", ending: ["e","en","e"], context: "Weak Nom / Weak Dat / Weak Acc" },
  { sentence: "Ein ehrgeizig__ Projekt erfordert lang__ Planung.", ending: ["es","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Die klar__ Antwort überzeugte den skeptisch__ Zuhörer sofort.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Mit groß__ Engagement verfolgt sie ihre beruflich__ Ziele.", ending: ["em","e"], context: "Strong Dat / Strong Acc" },
  { sentence: "Der ruhig__ Ton verbessert die schwierig__ Situation.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },

  { sentence: "Ein alt__ Problem braucht eine neu__ Lösung.", ending: ["es","e"], context: "Mixed Nom / Mixed Acc" },
  { sentence: "Die modern__ Architektur prägt das städtisch__ Bild.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },
  { sentence: "Mit stark__ Motivation erreicht man ehrgeizig__ Ziele.", ending: ["er","e"], context: "Strong Dat / Strong Acc" },
  { sentence: "Der logisch__ Aufbau erleichtert das verständlich__ Lernen.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },
  { sentence: "Ein wertvoll__ Hinweis rettete die kritisch__ Situation.", ending: ["er","e"], context: "Mixed Nom / Weak Acc" },

  { sentence: "Die schnell__ Reaktion verhinderte den ernst__ Schaden.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Mit ruhig__ Stimme beantwortete er die schwierig__ Frage.", ending: ["er","e"], context: "Strong Dat / Weak Acc" },
  { sentence: "Ein effizient__ System spart kostbar__ Zeit.", ending: ["es","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Der engagiert__ Einsatz stärkt das gemeinsam__ Ziel.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },
  { sentence: "Trotz hoh__ Belastung blieb er mental stark__.", ending: ["er",""], context: "Strong Gen / Predicative" },

  { sentence: "Die sorgfältig__ Planung verhindert unnötig__ Fehler.", ending: ["e","e"], context: "Weak Nom / Strong Acc" },
  { sentence: "Ein klar__ Konzept verbessert die intern__ Abläufe.", ending: ["es","en"], context: "Mixed Nom / Weak Acc" },
  { sentence: "Mit neu__ Ideen belebt er die kreativ__ Atmosphäre.", ending: ["en","e"], context: "Strong Dat / Weak Acc" },
  { sentence: "Der kritisch__ Blick erkennt selbst klein__ Details.", ending: ["e","e"], context: "Weak Nom / Strong Acc" },
  { sentence: "Ein mutig__ Schritt verändert das beruflich__ Leben.", ending: ["er","e"], context: "Mixed Nom / Weak Acc" },

  { sentence: "Die sachlich__ Diskussion klärte die strittig__ Punkte.", ending: ["e","en"], context: "Weak Nom / Weak Acc" },
  { sentence: "Mit fest__ Entschluss verfolgte sie ihr persönlich__ Ziel.", ending: ["em","es"], context: "Strong Dat / Mixed Acc" },
  { sentence: "Ein stabil__ Fundament trägt das massiv__ Gebäude.", ending: ["es","e"], context: "Mixed Nom / Weak Acc" },
  { sentence: "Der respektvoll__ Umgang stärkt das menschlich__ Vertrauen.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },
  { sentence: "Trotz hart__ Arbeit blieb der verdient__ Erfolg aus.", ending: ["er","e"], context: "Strong Gen / Weak Nom" },

  { sentence: "Die freundlich__ Geste zeigte ehrlich__ Dankbarkeit.", ending: ["e","e"], context: "Weak Nom / Strong Acc" },
  { sentence: "Ein sinnvoll__ Vorschlag verbessert die intern__ Kommunikation.", ending: ["er","e"], context: "Mixed Nom / Weak Acc" },
  { sentence: "Mit groß__ Geduld erklärt sie die kompliziert__ Regeln.", ending: ["er","en"], context: "Strong Dat / Weak Acc" },
  { sentence: "Der präzis__ Ablauf verhindert technisch__ Fehler.", ending: ["e","e"], context: "Weak Nom / Strong Acc" },
  { sentence: "Ein zuverlässig__ Partner sichert langfristig__ Stabilität.", ending: ["er","e"], context: "Mixed Nom / Strong Acc" },

  { sentence: "Die offen__ Haltung fördert konstruktiv__ Gespräche.", ending: ["e","e"], context: "Weak Nom / Strong Acc" },
  { sentence: "Mit ruhig__ Gelassenheit meistert er stressig__ Situationen.", ending: ["er","e"], context: "Strong Dat / Strong Acc" },
  { sentence: "Ein klar__ Ziel motiviert engagiert__ Mitarbeiter.", ending: ["es","e"], context: "Mixed Nom / Strong Acc" },
  { sentence: "Der ehrlich__ Austausch stärkt das gegenseitig__ Vertrauen.", ending: ["e","e"], context: "Weak Nom / Weak Acc" },
  { sentence: "Trotz groß__ Verantwortung blieb er menschlich nah__.", ending: ["er",""], context: "Strong Gen / Predicative" },

  { sentence: "Die ruhig__ Umgebung unterstützt konzentriert__ Arbeiten.", ending: ["e","es"], context: "Weak Nom / Mixed Acc" },
  { sentence: "Ein flexibel__ System passt sich schnell__ Anforderungen an.", ending: ["es","en"], context: "Mixed Nom / Weak Dat" },
  { sentence: "Mit neu__ Energie beginnt sie den spannend__ Abschnitt.", ending: ["er","en"], context: "Strong Dat / Weak Acc" },
  { sentence: "Der kritisch__ Bericht deckt schwer__ Fehler auf.", ending: ["e","e"], context: "Weak Nom / Strong Acc" },
  { sentence: "Ein positiv__ Ergebnis stärkt das beruflich__ Selbstvertrauen.", ending: ["es","e"], context: "Mixed Nom / Weak Acc" }
];
