const mixedExercises = [
    // --- NOMINATIVE (M: -er, F: -e, N: -es, P: -en) ---
    { sentence: "Ein gut__ Freund ist wichtig.", ending: "er", context: "Nom / Masc" },
    { sentence: "Eine klein__ Katze spielt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein neu__ Auto ist teuer.", ending: "es", context: "Nom / Neut" },
    { sentence: "Keine gut__ Ideen heute.", ending: "en", context: "Nom / Plur" },
    { sentence: "Mein alt__ Fahrrad ist blau.", ending: "es", context: "Nom / Neut" },
    { sentence: "Dein schick__ Anzug ist neu.", ending: "er", context: "Nom / Masc" },
    { sentence: "Ihre nett__ Mutter ruft an.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein hoh__ Baum steht da.", ending: "er", context: "Nom / Masc" },
    { sentence: "Eine spannend__ Reise beginnt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Unser alt__ Hund schläft.", ending: "er", context: "Nom / Masc" },
    { sentence: "Ein dunkel__ Zimmer ist gruselig.", ending: "es", context: "Nom / Neut" },
    { sentence: "Kein gesund__ Mensch raucht.", ending: "er", context: "Nom / Masc" },
    { sentence: "Eine hölzern__ Brücke ist dort.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein leer__ Glas ist hier.", ending: "es", context: "Nom / Neut" },
    { sentence: "Euer groß__ Garten ist schön.", ending: "er", context: "Nom / Masc" },
    { sentence: "Ein schwierig__ Rätsel gelöst.", ending: "es", context: "Nom / Neut" },
    { sentence: "Eine fleißig__ Biene summt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Seine neu__ Uhr glänzt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein tief__ See ist dort.", ending: "er", context: "Nom / Masc" },
    { sentence: "Keine teuer__ Miete zahlen.", ending: "en", context: "Nom / Plur" },
    { sentence: "Ein sonnig__ Tag heute.", ending: "er", context: "Nom / Masc" },
    { sentence: "Eine warm__ Jacke brauchen.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein hart__ Ei essen.", ending: "es", context: "Nom / Neut" },
    { sentence: "Mein klein__ Bruder nervt.", ending: "er", context: "Nom / Masc" },
    { sentence: "Ein hölzern__ Löffel liegt da.", ending: "er", context: "Nom / Masc" },

    // --- ACCUSATIVE (M: -en, F: -e, N: -es, P: -en) ---
    { sentence: "Ich esse einen rot__ Apfel.", ending: "en", context: "Acc / Masc" },
    { sentence: "Er liest ein spannend__ Buch.", ending: "es", context: "Acc / Neut" },
    { sentence: "Wir suchen eine frei__ Wohnung.", ending: "e", context: "Acc / Fem" },
    { sentence: "Siehst du meine neu__ Schuhe?", ending: "en", context: "Acc / Plur" },
    { sentence: "Ich trinke einen heiß__ Tee.", ending: "en", context: "Acc / Masc" },
    { sentence: "Er kauft ein gebraucht__ Auto.", ending: "es", context: "Acc / Neut" },
    { sentence: "Wir haben keine groß__ Probleme.", ending: "en", context: "Acc / Plur" },
    { sentence: "Ich brauche eine scharf__ Schere.", ending: "e", context: "Acc / Fem" },
    { sentence: "Haben Sie einen gut__ Wein?", ending: "en", context: "Acc / Masc" },
    { sentence: "Er wünscht ein froh__ Fest.", ending: "es", context: "Acc / Neut" },
    { sentence: "Ich besuche meine krank__ Tante.", ending: "e", context: "Acc / Fem" },
    { sentence: "Sie trägt ein weiß__ Kleid.", ending: "es", context: "Acc / Neut" },
    { sentence: "Hast du einen hoh__ Turm gesehen?", ending: "en", context: "Acc / Masc" },
    { sentence: "Wir planen eine lang__ Reise.", ending: "e", context: "Acc / Fem" },
    { sentence: "Er besitzt ein hölzern__ Boot.", ending: "es", context: "Acc / Neut" },
    { sentence: "Ich mag deine bunt__ Haare.", ending: "en", context: "Acc / Plur" },
    { sentence: "Sie sucht einen günstig__ Flug.", ending: "en", context: "Acc / Masc" },
    { sentence: "Ich höre eine laut__ Musik.", ending: "e", context: "Acc / Fem" },
    { sentence: "Wir kochen ein lecker__ Gericht.", ending: "es", context: "Acc / Neut" },
    { sentence: "Siehst er seine alt__ Freunde?", ending: "en", context: "Acc / Plur" },
    { sentence: "Ich kaufe einen hölzern__ Tisch.", ending: "en", context: "Acc / Masc" },
    { sentence: "Hast du ein frei__ Zimmer?", ending: "es", context: "Acc / Neut" },
    { sentence: "Wir sehen eine hoh__ Mauer.", ending: "e", context: "Acc / Fem" },
    { sentence: "Sie trägt eine gold__ Kette.", ending: "e", context: "Acc / Fem" },
    { sentence: "Ich trinke einen süß__ Saft.", ending: "en", context: "Acc / Masc" },

    // --- DATIVE (Always -en) ---
    { sentence: "Ich helfe meinem alt__ Opa.", ending: "en", context: "Dat / Masc" },
    { sentence: "Wir wohnen in einer klein__ Stadt.", ending: "en", context: "Dat / Fem" },
    { sentence: "Er spielt mit einem neu__ Spielzeug.", ending: "en", context: "Dat / Neut" },
    { sentence: "Mit meinen best__ Freunden.", ending: "en", context: "Dat / Plur" },
    { sentence: "Ich schreibe mit einem blau__ Stift.", ending: "en", context: "Dat / Masc" },
    { sentence: "In einer hoh__ Etage.", ending: "en", context: "Dat / Fem" },
    { sentence: "Aus einem hölzern__ Fass.", ending: "en", context: "Dat / Neut" },
    { sentence: "Zu seinen neu__ Nachbarn.", ending: "en", context: "Dat / Plur" },
    { sentence: "Bei einem gut__ Glas Wein.", ending: "en", context: "Dat / Neut" },
    { sentence: "Seit einer halb__ Stunde.", ending: "en", context: "Dat / Fem" },
    { sentence: "Mit deinem teuer__ Laptop.", ending: "en", context: "Dat / Masc" },
    { sentence: "In einem dunkel__ Wald.", ending: "en", context: "Dat / Masc" },
    { sentence: "Von einer bekannt__ Firma.", ending: "en", context: "Dat / Fem" },
    { sentence: "An einem sonnig__ Nachmittag.", ending: "en", context: "Dat / Masc" },
    { sentence: "Mit einer schmutzig__ Gabel.", ending: "en", context: "Dat / Fem" },
    { sentence: "Hinter einem hoh__ Zaun.", ending: "en", context: "Dat / Masc" },
    { sentence: "Unter einem hölzern__ Tisch.", ending: "en", context: "Dat / Masc" },
    { sentence: "Dank deiner schnell__ Hilfe.", ending: "en", context: "Dat / Fem" },
    { sentence: "Aus einem tief__ Tal.", ending: "en", context: "Dat / Neut" },
    { sentence: "Nach einem lang__ Gespräch.", ending: "en", context: "Dat / Neut" },
    { sentence: "Mit einer scharf__ Axt.", ending: "en", context: "Dat / Fem" },
    { sentence: "Von einem hoh__ Berg.", ending: "en", context: "Dat / Masc" },
    { sentence: "Zu einem klein__ Preis.", ending: "en", context: "Dat / Masc" },
    { sentence: "In einer hölzern__ Hütte.", ending: "en", context: "Dat / Fem" },
    { sentence: "Seit einem ganz__ Jahr.", ending: "en", context: "Dat / Neut" },

    // --- GENITIVE (Always -en) ---
    { sentence: "Wegen eines schwer__ Fehlers.", ending: "en", context: "Gen / Masc" },
    { sentence: "Während meiner kurz__ Pause.", ending: "en", context: "Gen / Fem" },
    { sentence: "Das Ende eines lang__ Films.", ending: "en", context: "Gen / Masc" },
    { sentence: "Inmitten meiner neu__ Wohnung.", ending: "en", context: "Gen / Fem" },
    { sentence: "Die Farbe deines neu__ Autos.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Meinung eines klug__ Mannes.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Duft einer frisch__ Blume.", ending: "en", context: "Gen / Fem" },
    { sentence: "Die Blätter meiner welk__ Pflanze.", ending: "en", context: "Gen / Fem" },
    { sentence: "Trotz eines hoh__ Preises.", ending: "en", context: "Gen / Masc" },
    { sentence: "Wegen eines klein__ Problems.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Hilfe seiner gut__ Freunde.", ending: "en", context: "Gen / Plur" },
    { sentence: "Innerhalb eines kurz__ Zeitraums.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Inhalt deines hölzern__ Koffers.", ending: "en", context: "Gen / Masc" },
    { sentence: "Die Tür einer alt__ Kirche.", ending: "en", context: "Gen / Fem" },
    { sentence: "Aufgrund eines dumm__ Zufalls.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Preis eines modern__ Handys.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Stimme unserer neu__ Sängerin.", ending: "en", context: "Gen / Fem" },
    { sentence: "Trotz deines hoh__ Alters.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Qualität eines gut__ Weins.", ending: "en", context: "Gen / Masc" },
    { sentence: "Während eines spannend__ Spiels.", ending: "en", context: "Gen / Neut" },
    { sentence: "Das Ende meines lang__ Tages.", ending: "en", context: "Gen / Masc" },
    { sentence: "Die Farbe seiner rot__ Haare.", ending: "en", context: "Gen / Plur" },
    { sentence: "Wegen eines hölzern__ Zauns.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Titel eines hoh__ Amtes.", ending: "en", context: "Gen / Neut" },
    { sentence: "Das Licht eines hell__ Sterns.", ending: "en", context: "Gen / Masc" }
];