const mixedExercises = [
    // --- NOMINATIVE (M: -er, F: -e, N: -es, P: -en) ---
    { sentence: "Ein gut__ Freund hilft immer.", ending: "er", context: "Nom / Masc" },
    { sentence: "Eine klein__ Katze schläft.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein neu__ Haus ist teuer.", ending: "es", context: "Nom / Neut" },
    { sentence: "Keine gut__ Nachrichten heute.", ending: "en", context: "Nom / Plur" },
    { sentence: "Mein alt__ Fahrrad quietscht.", ending: "es", context: "Nom / Neut" },
    { sentence: "Dein schick__ Anzug passt gut.", ending: "er", context: "Nom / Masc" },
    { sentence: "Ihre nett__ Schwester kommt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein hoh__ Baum steht dort.", ending: "er", context: "Nom / Masc" },
    { sentence: "Eine spannend__ Reise beginnt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Unser alt__ Lehrer geht.", ending: "er", context: "Nom / Masc" },
    { sentence: "Ein dunkel__ Zimmer ist ungemütlich.", ending: "es", context: "Nom / Neut" },
    { sentence: "Kein gesund__ Mensch raucht.", ending: "er", context: "Nom / Masc" },
    { sentence: "Eine hölzern__ Brücke führt rüber.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein leer__ Glas steht hier.", ending: "es", context: "Nom / Neut" },
    { sentence: "Euer groß__ Hund bellt.", ending: "er", context: "Nom / Masc" },
    { sentence: "Ein schwierig__ Rätsel wartet.", ending: "es", context: "Nom / Neut" },
    { sentence: "Eine fleißig__ Biene sammelt Honig.", ending: "e", context: "Nom / Fem" },
    { sentence: "Seine neu__ Uhr ist kaputt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Ein tief__ See ist blau.", ending: "er", context: "Nom / Masc" },
    { sentence: "Keine teuer__ Kleidung nötig.", ending: "en", context: "Nom / Plur" },

    // --- ACCUSATIVE (M: -en, F: -e, N: -es, P: -en) ---
    { sentence: "Ich esse einen rot__ Apfel.", ending: "en", context: "Acc / Masc" },
    { sentence: "Er liest ein spannend__ Buch.", ending: "es", context: "Acc / Neut" },
    { sentence: "Wir suchen eine frei__ Wohnung.", ending: "e", context: "Acc / Fem" },
    { sentence: "Siehst du meine neu__ Schuhe?", ending: "en", context: "Acc / Plur" },
    { sentence: "Ich trinke einen heiß__ Tee.", ending: "en", context: "Acc / Masc" },
    { sentence: "Er kauft ein gebraucht__ Auto.", ending: "es", context: "Acc / Neut" },
    { sentence: "Wir haben keine groß__ Probleme.", ending: "en", context: "Acc / Plur" },
    { sentence: "Ich brauche eine scharf__ Schere.", ending: "e", context: "Acc / Fem" },
    { sentence: "Haben Sie einen gut__ Wein?", ending: "en", context: "Acc / Masc" },
    { sentence: "Er wünscht ein froh__ Fest.", ending: "es", context: "Acc / Neut" },
    { sentence: "Ich besuche meine krank__ Tante.", ending: "e", context: "Acc / Fem" },
    { sentence: "Sie trägt ein weiß__ Kleid.", ending: "es", context: "Acc / Neut" },
    { sentence: "Hast du einen hoh__ Turm gesehen?", ending: "en", context: "Acc / Masc" },
    { sentence: "Wir planen eine lang__ Wanderung.", ending: "e", context: "Acc / Fem" },
    { sentence: "Er besitzt ein hölzern__ Boot.", ending: "es", context: "Acc / Neut" },
    { sentence: "Ich mag deine bunt__ Haare.", ending: "en", context: "Acc / Plur" },
    { sentence: "Sie sucht einen günstig__ Flug.", ending: "en", context: "Acc / Masc" },
    { sentence: "Ich höre eine laut__ Musik.", ending: "e", context: "Acc / Fem" },
    { sentence: "Wir kochen ein lecker__ Gericht.", ending: "es", context: "Acc / Neut" },
    { sentence: "Sieht er seine alt__ Freunde?", ending: "en", context: "Acc / Plur" },

    // --- DATIVE (ALL: -en) ---
    { sentence: "Ich helfe meinem alt__ Opa.", ending: "en", context: "Dat / Masc" },
    { sentence: "Wir wohnen in einer klein__ Stadt.", ending: "en", context: "Dat / Fem" },
    { sentence: "Er spielt mit einem neu__ Spielzeug.", ending: "en", context: "Dat / Neut" },
    { sentence: "Mit meinen best__ Freunden.", ending: "en", context: "Dat / Plur" },
    { sentence: "Ich schreibe mit einem blau__ Stift.", ending: "en", context: "Dat / Masc" },
    { sentence: "In einer hoh__ Etage wohnen.", ending: "en", context: "Dat / Fem" },
    { sentence: "Aus einem hölzern__ Fass trinken.", ending: "en", context: "Dat / Neut" },
    { sentence: "Zu seinen neu__ Nachbarn gehen.", ending: "en", context: "Dat / Plur" },
    { sentence: "Bei einem gut__ Glas Wein.", ending: "en", context: "Dat / Neut" },
    { sentence: "Seit einer halb__ Stunde.", ending: "en", context: "Dat / Fem" },
    { sentence: "Mit deinem teuer__ Laptop.", ending: "en", context: "Dat / Masc" },
    { sentence: "In einem dunkl__ Wald.", ending: "en", context: "Dat / Masc" },
    { sentence: "Von einer bekannt__ Firma.", ending: "en", context: "Dat / Fem" },
    { sentence: "An einem sonnig__ Nachmittag.", ending: "en", context: "Dat / Masc" },
    { sentence: "Mit einer schmutzig__ Gabel.", ending: "en", context: "Dat / Fem" },
    { sentence: "Hinter einem hoh__ Zaun.", ending: "en", context: "Dat / Masc" },
    { sentence: "Unter einem hölzern__ Tisch.", ending: "en", context: "Dat / Masc" },
    { sentence: "Dank deiner schnell__ Hilfe.", ending: "en", context: "Dat / Fem" },
    { sentence: "Aus einem tief__ Tal.", ending: "en", context: "Dat / Neut" },
    { sentence: "Nach einem lang__ Gespräch.", ending: "en", context: "Dat / Neut" },

    // --- GENITIVE (ALL: -en) ---
    { sentence: "Wegen eines schwer__ Fehlers.", ending: "en", context: "Gen / Masc" },
    { sentence: "Während meiner kurz__ Pause.", ending: "en", context: "Gen / Fem" },
    { sentence: "Das Ende eines lang__ Films.", ending: "en", context: "Gen / Masc" },
    { sentence: "Inmitten meiner neu__ Wohnung.", ending: "en", context: "Gen / Fem" },
    { sentence: "Die Farbe deines neu__ Autos.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Meinung eines klug__ Mannes.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Duft einer frisch__ Blume.", ending: "en", context: "Gen / Fem" },
    { sentence: "Die Blätter meiner welk__ Pflanze.", ending: "en", context: "Gen / Fem" },
    { sentence: "Trotz eines hoh__ Preises.", ending: "en", context: "Gen / Masc" },
    { sentence: "Wegen eines klein__ Missverständnisses.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Hilfe seiner gut__ Freunde.", ending: "en", context: "Gen / Plur" },
    { sentence: "Innerhalb eines kurz__ Zeitraums.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Inhalt deines hölzern__ Koffers.", ending: "en", context: "Gen / Masc" },
    { sentence: "Die Tür einer alt__ Kirche.", ending: "en", context: "Gen / Fem" },
    { sentence: "Aufgrund eines dumm__ Zufalls.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Preis eines modern__ Handys.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Stimme unserer neu__ Sängerin.", ending: "en", context: "Gen / Fem" },
    { sentence: "Trotz de
