const weakExercises = [
    // --- NOMINATIVE ---
    { sentence: "Der alt__ Baum ist groß.", ending: "e", context: "Nom / Masc" },
    { sentence: "Die jung__ Frau lacht.", ending: "e", context: "Nom / Fem" },
    { sentence: "Das neu__ Auto glänzt.", ending: "e", context: "Nom / Neut" },
    { sentence: "Die klein__ Kinder spielen.", ending: "en", context: "Nom / Plur" },
    { sentence: "Der scharf__ Senf brennt.", ending: "e", context: "Nom / Masc" },
    { sentence: "Die süß__ Limonade erfrischt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Das kalt__ Wasser hilft.", ending: "e", context: "Nom / Neut" },
    { sentence: "Die teuer__ Uhren sind weg.", ending: "en", context: "Nom / Plur" },
    { sentence: "Der krank__ Hund schläft.", ending: "e", context: "Nom / Masc" },
    { sentence: "Die schmutzig__ Wäsche liegt dort.", ending: "e", context: "Nom / Fem" },
    { sentence: "Das kaputt__ Fenster zieht.", ending: "e", context: "Nom / Neut" },
    { sentence: "Die fleißig__ Schüler lernen.", ending: "en", context: "Nom / Plur" },
    { sentence: "Der hoh__ Berg ist weiß.", ending: "e", context: "Nom / Masc" },
    { sentence: "Die schmal__ Straße ist leer.", ending: "e", context: "Nom / Fem" },
    { sentence: "Das leise__ Radio stört nicht.", ending: "e", context: "Nom / Neut" },
    { sentence: "Die grün__ Äpfel sind sauer.", ending: "en", context: "Nom / Plur" },
    { sentence: "Der lang__ Film ist langweilig.", ending: "e", context: "Nom / Masc" },
    { sentence: "Die hölzern__ Tür klemmt.", ending: "e", context: "Nom / Fem" },
    { sentence: "Das golden__ Ei ist weg.", ending: "e", context: "Nom / Neut" },
    { sentence: "Die laut__ Nachbarn nerven.", ending: "en", context: "Nom / Plur" },

    // --- ACCUSATIVE ---
    { sentence: "Ich sehe den schwarz__ Hund.", ending: "en", context: "Acc / Masc" },
    { sentence: "Er kauft die rot__ Blume.", ending: "e", context: "Acc / Fem" },
    { sentence: "Wir essen das frisch__ Brot.", ending: "e", context: "Acc / Neut" },
    { sentence: "Sie liebt die bunt__ Bilder.", ending: "en", context: "Acc / Plur" },
    { sentence: "Ich trinke den heiß__ Tee.", ending: "en", context: "Acc / Masc" },
    { sentence: "Hast du die neu__ Zeitung?", ending: "e", context: "Acc / Fem" },
    { sentence: "Ich mag das dunkel__ Bier.", ending: "e", context: "Acc / Neut" },
    { sentence: "Siehst du die hoh__ Häuser?", ending: "en", context: "Acc / Plur" },
    { sentence: "Er schreibt den kurz__ Brief.", ending: "en", context: "Acc / Masc" },
    { sentence: "Sie sucht die verloren__ Kette.", ending: "e", context: "Acc / Fem" },
    { sentence: "Wir hören das laut__ Geräusch.", ending: "e", context: "Acc / Neut" },
    { sentence: "Ich kenne die nett__ Nachbarn.", ending: "en", context: "Acc / Plur" },
    { sentence: "Verkaufst du den alt__ Wagen?", ending: "en", context: "Acc / Masc" },
    { sentence: "Ich koche die gelb__ Suppe.", ending: "e", context: "Acc / Fem" },
    { sentence: "Sie trägt das weiß__ Kleid.", ending: "e", context: "Acc / Neut" },
    { sentence: "Ich putze die dreckig__ Schuhe.", ending: "en", context: "Acc / Plur" },
    { sentence: "Wir besuchen den botanisch__ Garten.", ending: "en", context: "Acc / Masc" },
    { sentence: "Er liest die spannend__ Geschichte.", ending: "e", context: "Acc / Fem" },
    { sentence: "Sie wäscht das schmutzig__ Geschirr.", ending: "e", context: "Acc / Neut" },
    { sentence: "Ich mag die italienisch__ Lieder.", ending: "en", context: "Acc / Plur" },

    // --- DATIVE ---
    { sentence: "Ich helfe dem alt__ Mann.", ending: "en", context: "Dat / Masc" },
    { sentence: "Wir wohnen bei der freundlich__ Dame.", ending: "en", context: "Dat / Fem" },
    { sentence: "Er spielt mit dem klein__ Kind.", ending: "en", context: "Dat / Neut" },
    { sentence: "Das gehört den brav__ Kindern.", ending: "en", context: "Dat / Plur" },
    { sentence: "Ich antworte dem streng__ Lehrer.", ending: "en", context: "Dat / Masc" },
    { sentence: "Sie geht zu der neu__ Ärztin.", ending: "en", context: "Dat / Fem" },
    { sentence: "Wir sitzen an dem runden__ Tisch.", ending: "en", context: "Dat / Masc" },
    { sentence: "Das liegt auf dem grün__ Gras.", ending: "en", context: "Dat / Neut" },
    { sentence: "Er arbeitet in den hoh__ Bergen.", ending: "en", context: "Dat / Plur" },
    { sentence: "Ich fahre mit dem schnell__ Zug.", ending: "en", context: "Dat / Masc" },
    { sentence: "Wir sprechen von der hoh__ Mauer.", ending: "en", context: "Dat / Fem" },
    { sentence: "Ich danke dem nett__ Personal.", ending: "en", context: "Dat / Neut" },
    { sentence: "Sie tanzt mit den jung__ Männern.", ending: "en", context: "Dat / Plur" },
    { sentence: "Hinter dem hölzern__ Zaun.", ending: "en", context: "Dat / Masc" },
    { sentence: "Vor der groß__ Prüfung.", ending: "en", context: "Dat / Fem" },
    { sentence: "Aus dem offen__ Fenster.", ending: "en", context: "Dat / Neut" },
    { sentence: "Gegenüber den hoh__ Türmen.", ending: "en", context: "Dat / Plur" },
    { sentence: "Nach dem lang__ Winter.", ending: "en", context: "Dat / Masc" },
    { sentence: "Seit der letzt__ Woche.", ending: "en", context: "Dat / Fem" },
    { sentence: "Bei dem sonnig__ Wetter.", ending: "en", context: "Dat / Neut" },

    // --- GENITIVE ---
    { sentence: "Das Dach des alt__ Hauses.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Farbe der neu__ Tür.", ending: "en", context: "Gen / Fem" },
    { sentence: "Der Preis des modern__ Autos.", ending: "en", context: "Gen / Neut" },
    { sentence: "Wegen des stark__ Regens.", ending: "en", context: "Gen / Masc" },
    { sentence: "Die Stimme des klein__ Jungen.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Duft der frisch__ Blume.", ending: "en", context: "Gen / Fem" },
    { sentence: "Das Ende des spannend__ Buches.", ending: "en", context: "Gen / Neut" },
    { sentence: "Die Namen der neu__ Schüler.", ending: "en", context: "Gen / Plur" },
    { sentence: "Trotz des hoh__ Preises.", ending: "en", context: "Gen / Masc" },
    { sentence: "Während der lang__ Fahrt.", ending: "en", context: "Gen / Fem" },
    { sentence: "Die Qualität des billig__ Weins.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Titel der bekannt__ Oper.", ending: "en", context: "Gen / Fem" },
    { sentence: "Das Licht des hell__ Sterns.", ending: "en", context: "Gen / Masc" },
    { sentence: "Die Blätter der alt__ Eiche.", ending: "en", context: "Gen / Fem" },
    { sentence: "Aufgrund des schwer__ Fehlers.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Besitzer des neu__ Ladens.", ending: "en", context: "Gen / Masc" },
    { sentence: "Die Form des rund__ Tisches.", ending: "en", context: "Gen / Masc" },
    { sentence: "Der Inhalt der kurz__ Nachricht.", ending: "en", context: "Gen / Fem" },
    { sentence: "Die Fenster des hoh__ Gebäudes.", ending: "en", context: "Gen / Neut" },
    { sentence: "Der Geschmack der süß__ Frucht.", ending: "en", context: "Gen / Fem" },

    // --- DETERMINERS (DIESER, JEDER, JENER, ETC) ---
    { sentence: "Dieser alt__ Mann ist nett.", ending: "e", context: "Nom / Masc" },
    { sentence: "Ich mag dieses blau__ Hemd.", ending: "e", context: "Acc / Neut" },
    { sentence: "Jeder gut__ Tag zählt.", ending: "e", context: "Nom / Masc" },
    { sentence: "Welche schön__ Blume meinst du?", ending: "e", context: "Acc / Fem" },
    { sentence: "Alle klein__ Tiere schlafen.", ending: "en", context: "Nom / Plur" },
    { sentence: "In jedem klein__ Laden.", ending: "en", context: "Dat / Masc" },
    { sentence: "Jene hoh__ Berge sind fern.", ending: "en", context: "Nom / Plur" },
    { sentence: "Solches frisch__ Brot ist gut.", ending: "e", context: "Nom / Neut" },
    { sentence: "Ich sehe diese jung__ Frau.", ending: "e", context: "Acc / Fem" },
    { sentence: "Nach jedem lang__ Lauf.", ending: "en", context: "Dat / Masc" },
    { sentence: "Dieses hoh__ Gras stört.", ending: "e", context: "Nom / Neut" },
    { sentence: "Manche alt__ Geschichten.", ending: "en", context: "Nom / Plur" },
    { sentence: "Ich nehme diesen rot__ Apfel.", ending: "en", context: "Acc / Masc" },
    { sentence: "Mit jener alt__ Kamera.", ending: "en", context: "Dat / Fem" },
    { sentence: "Welches neu__ Auto kaufst du?", ending: "e", context: "Acc / Neut" },
    { sentence: "In solchen hoh__ Schuhen.", ending: "en", context: "Dat / Plur" },
    { sentence: "Dieser hölzern__ Tisch ist alt.", ending: "e", context: "Nom / Masc" },
    { sentence: "Alle wichtig__ Dokumente.", ending: "en", context: "Nom / Plur" },
    { sentence: "Jedes klein__ Detail ist wichtig.", ending: "e", context: "Nom / Neut" },
    { sentence: "Ich kenne jenen hoh__ Baum.", ending: "en", context: "Acc / Masc" }
];
